### ISSUE TITLE
Insert fails if Drupal compatibility is disabled

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/insert#11] opened 2021-11-08 09:41 UTC
Not sure if this can be reproduced as I don't know what factor is causing this issue on one site but not another.

## Issue
![ltK5lGDFHI](https://user-images.githubusercontent.com/20357797/140718707-4dd697a4-57a3-47ea-b12b-ca2b7c0f767e.gif)
![chrome_LRzbN5fhE8](https://user-images.githubusercontent.com/20357797/140718725-4210d0f1-fe0b-4815-871f-f9dd662761ba.png)

## Site working ok
![56D59sza9C](https://user-images.githubusercontent.com/20357797/140719223-a638c94d-5e48-4118-80ee-4661ea48d57c.gif)

Can anyone give me any clues as to what might be causing this on one site but not another?  I'm able to upload images to this site on a content type without insert enabled, hence why I think this may have some link to Insert.

**Comment by indigoxela** [comment] 2021-11-08 10:08
> Can anyone give me any clues as to what might be causing this...

Do you have access to the webserver/php logs? That might at least give a hint.  500s are often (not always) caused by file system permission problems.

Also: are you sure, this is caused by the insert module? Or does it happen with *all* fields with upload functionality (image, file...)?

**Comment by yorkshire-pudding** [comment] 2021-11-08 10:23
Hi @indigoxela - thanks for getting back to me.  If I upload on a content type that doesn't have insert on the same site, then it uploads without a problem.  

However, your prompt to look at the logs has identified the culprit: One site has drupal compatibility enabled, and insert works.  The other doesn't and it doesn't work.

![image](https://user-images.githubusercontent.com/20357797/140724344-a3ce4879-a910-461f-a467-31067547548f.png)
![image](https://user-images.githubusercontent.com/20357797/140724827-fbbd1fb9-622f-4363-83c2-e8f0e4c4bc75.png)

Looks like this is the offending function:
![image](https://user-images.githubusercontent.com/20357797/140725280-d5660f95-6303-4956-9f3a-7e99396ddbd7.png)

**Comment by yorkshire-pudding** [comment] 2021-11-08 10:29
I'll try and see if I can fix this and put a pull request in

**Comment by ghost** [comment] 2021-11-08 10:37
Sounds like it just need a one-line change to this: https://docs.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/backdrop_http_build_query/1

**Comment by yorkshire-pudding** [comment] 2021-11-08 10:46
> Sounds like it just need a one-line change to this: https://docs.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/backdrop_http_build_query/1

Aye - I found that pretty quickly.

**Comment by ghost** [comment] 2021-11-08 10:53
Thanks @yorkshire-pudding, PR merged.

**Closed as completed by ghost** 2021-11-08 10:53 UTC
